; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

	TITLE	c:\Users\PROGMAN\workspace\idasdk61\plugins\bochs_user\test.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_rrrr
_BSS	SEGMENT
_a	DD	01fa400H DUP (?)
_BSS	ENDS
; Function compile flags: /Odtp
; File c:\users\progman\workspace\idasdk61\plugins\bochs_user\test.c
_TEXT	SEGMENT
_rrrr	PROC

; 4    : {

	push	ebp
	mov	ebp, esp

; 5    : 	return a;

	mov	eax, OFFSET _a

; 6    : }

	pop	ebp
	ret	0
_rrrr	ENDP
_TEXT	ENDS
END
